on:
  push:
    branches:
      - master

name: Test bf

jobs:
  test:
    strategy:
      matrix:
        go-version: [ 1.16.x ]
        platform: [ ubuntu-latest ]
    runs-on: ubuntu-latest

    steps:
      - name: Install go
        uses: actions/setup-go@v2
        with:
          go-version: ${{matrix.go-version}}

      - name: Checkout code
        uses: actions/checkout@v2

      - run: mkdir coverage

      - name: Run tests
        run: go test -v ./... -v -covermode=count -coverprofile=./coverage/coverage.out

      - name: Generate HTML coverage output
        run: go tool cover -html=./coverage/coverage.out -o ./coverage/coverage.html

      - name: Archive code coverage results
        uses: actions/upload-artifact@v2
        with:
          name: coverage-report
          path: ./coverage/coverage.html
